version: '3.8'

services:
  cleanarch-api:
    build:
      context: .
      dockerfile: /src/CleanArchMediatR.Template.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Provider=MSSQL
      - ConnectionStrings__Default=Server=mssql;Database=CleanArchDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=True;TrustServerCertificate=True;

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
